# Generated by Django 4.0.10 on 2024-08-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symtom',
            new_name='symptom',
        ),
    ]
